# Generated by Django 4.1.4 on 2023-03-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile_location_profile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='scores',
            field=models.IntegerField(default=0),
        ),
    ]
