# Generated by Django 4.1.4 on 2023-03-02 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_rename_task_coursetask_tasktype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_profile_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choiceCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('lessons', models.ManyToManyField(to='course.coursetask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('updated_at', 'created_at'),
            },
        ),
    ]
