# Generated by Django 5.0.6 on 2024-06-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='is_public',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
