# Generated by Django 4.2.3 on 2023-09-13 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='initialRequirements',
        ),
        migrations.RemoveField(
            model_name='course',
            name='knowledges',
        ),
        migrations.RemoveField(
            model_name='course',
            name='whatAreUWillLearn',
        ),
    ]
