# Generated by Django 4.1.4 on 2023-01-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='courses'),
        ),
    ]
