# Generated by Django 4.1.4 on 2023-01-10 02:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.AddField(
            model_name='course',
            name='about',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='course',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='courses/certificates'),
        ),
        migrations.AddField(
            model_name='course',
            name='commentsCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='initialRequirements',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='lessonsCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='themesCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='viewCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='whatAreUWillLearn',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='coursetask',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursetitle',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses'),
        ),
    ]
