# Generated by Django 5.0.6 on 2024-07-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_taskcomment_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursereview',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='title',
            name='tasks',
            field=models.ManyToManyField(blank=True, default=[], related_name='title_tasks', through='course.TaskOrder', to='course.task'),
        ),
    ]
