# Generated by Django 4.2.5 on 2023-09-30 05:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_task_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000),
        ),
    ]
