# Generated by Django 4.1.4 on 2023-01-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetask',
            name='place',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='coursetitle',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='coursetitle',
            name='place',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
