# Generated by Django 5.0.6 on 2024-06-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_options_taskcomment_task_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
