# Generated by Django 4.2.2 on 2023-10-04 12:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_alter_course_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTaskProgress',
            new_name='UserCourseProgress',
        ),
    ]
