# Generated by Django 4.1.4 on 2022-12-27 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('VIDEO', 'VIDEO'), ('CODE', 'CODE'), ('TEST', 'TEST'), ('TEXT', 'TEXT')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos')),
                ('body', models.TextField(blank=True)),
                ('codeAnswer', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('courseTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursetitle')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.RemoveField(
            model_name='codetestcomment',
            name='codeTest',
        ),
        migrations.RemoveField(
            model_name='codetestcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='coursevideo',
            name='courseTitle',
        ),
        migrations.RemoveField(
            model_name='coursevideocomment',
            name='courseVideo',
        ),
        migrations.RemoveField(
            model_name='coursevideocomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='writecode',
            name='courseTitle',
        ),
        migrations.RemoveField(
            model_name='writecodecomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='writecodecomment',
            name='writeCode',
        ),
        migrations.DeleteModel(
            name='CodeTest',
        ),
        migrations.DeleteModel(
            name='CodeTestComment',
        ),
        migrations.DeleteModel(
            name='CourseVideo',
        ),
        migrations.DeleteModel(
            name='CourseVideoComment',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='WriteCode',
        ),
        migrations.DeleteModel(
            name='WriteCodeComment',
        ),
    ]
