# Generated by Django 4.1.4 on 2023-01-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_coursetask_place_coursetitle_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetitle',
            name='description',
        ),
    ]
