# Generated by Django 5.0.6 on 2024-07-29 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_coursereview_options_alter_title_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='tasks',
            new_name='title_tasks',
        ),
    ]
