# Generated by Django 4.2.5 on 2023-11-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codetask',
            old_name='text',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='codetask',
            name='users_who_completed_code',
        ),
        migrations.RemoveField(
            model_name='question',
            name='users_who_completed_question',
        ),
        migrations.AlterField(
            model_name='codetask',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(blank=True, choices=[('text', 'text'), ('video', 'video'), ('project', 'project'), ('questions', 'questions'), ('code', 'code')], max_length=10),
        ),
    ]
