# Generated by Django 5.0.6 on 2024-06-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_taskcomment_options_alter_taskcomment_text'),
        ('user', '0002_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reactions',
            field=models.ManyToManyField(blank=True, default=[], to='user.reaction'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='reactions',
            field=models.ManyToManyField(blank=True, default=[], to='user.reaction'),
        ),
    ]
