# Generated by Django 4.2.5 on 2023-11-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_text_codetask_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(blank=True, choices=[('TaskText', 'TaskText'), ('TaskVideo', 'TaskVideo'), ('TaskProject', 'TaskProject'), ('TaskQuestions', 'TaskQuestions'), ('TaskCode', 'TaskCode')], max_length=20),
        ),
    ]
