# Generated by Django 4.1.4 on 2023-01-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_coursetitle_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetask',
            name='task',
            field=models.CharField(blank=True, choices=[('video', 'video'), ('code', 'code'), ('test', 'test'), ('text', 'text')], max_length=10),
        ),
    ]
