# Generated by Django 4.1.4 on 2022-12-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_coursetask_remove_codetestcomment_codetest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetask',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coursetask',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursetask',
            name='codeAnswer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursetask',
            name='task',
            field=models.CharField(choices=[('video', 'video'), ('code', 'code'), ('test', 'test'), ('text', 'text')], max_length=10),
        ),
        migrations.AlterField(
            model_name='coursetask',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
