# Generated by Django 4.2.2 on 2023-10-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_usertaskprogress_usercourseprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskURLField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_on_repo', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='code_true_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(blank=True, choices=[('text', 'text'), ('video', 'video'), ('project', 'project'), ('code', 'code')], max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='url_on_repo',
            field=models.ManyToManyField(blank=True, to='course.taskurlfield'),
        ),
    ]
