# Generated by Django 4.2.2 on 2023-10-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_taskurlfield_task_code_true_answer_alter_task_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
