# Generated by Django 4.1.4 on 2023-01-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_coursetask_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetask',
            name='place',
        ),
    ]
