# Generated by Django 5.0.6 on 2024-06-20 06:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_taskcomment_reactions_taskcomment_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='taskCommentLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
