# Generated by Django 4.2.2 on 2023-10-04 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0006_task_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='users_who_completed',
            field=models.ManyToManyField(blank=True, related_name='users_who_completed_course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='users_who_completed',
            field=models.ManyToManyField(blank=True, related_name='users_who_completed_task', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserCourseProgress',
        ),
    ]
