# Generated by Django 4.2.2 on 2023-10-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_users_who_completed_task_users_who_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='users_who_completed',
            new_name='users_who_completed_course',
        ),
    ]
