# Generated by Django 4.1.4 on 2023-01-17 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_coursetask_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetask',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
