# Generated by Django 4.1.4 on 2023-01-31 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_coursecomment_commenttype_coursecomment_coursetask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomment',
            name='courseTask',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.coursetask'),
        ),
    ]
