# Generated by Django 4.1.4 on 2023-03-02 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_coursecomment_coursetask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursetask',
            old_name='task',
            new_name='taskType',
        ),
    ]
