# Generated by Django 4.2.5 on 2023-10-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_rename_users_who_completed_course_users_who_completed_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='point',
            new_name='points',
        ),
    ]
