# Generated by Django 5.0.6 on 2024-06-23 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_task_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reactions',
        ),
        migrations.AddField(
            model_name='task',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='task_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
