# Generated by Django 5.0.6 on 2024-08-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_achievement_alter_user_options_remove_user_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
