# Generated by Django 5.0.6 on 2024-08-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_achievement_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='type',
            field=models.CharField(choices=[('COURSE', 'Courses Completed'), ('TASK', 'Tasks Completed'), ('COMMENT', 'Comments Made'), ('DAY', 'Days Active')], max_length=10),
        ),
    ]
