# Generated by Django 4.1.4 on 2023-02-20 03:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_coursecomment_coursetask'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='article_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.article'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='article_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.article'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='message_en',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='message_ru',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
