# Generated by Django 4.1.4 on 2023-01-10 02:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bookmarksForCourse',
            field=models.ManyToManyField(default='', related_name='bookmarksForCourse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='commentsCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='likesForArticle',
            field=models.ManyToManyField(default='', related_name='likesForArticle', to=settings.AUTH_USER_MODEL),
        ),
    ]
