# Generated by Django 4.1.4 on 2023-02-20 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_tag_en_article_tag_ru_article_text_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tag_ru',
        ),
    ]
