# Generated by Django 4.1.4 on 2023-01-10 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_article_bookmarksforcourse_article_commentscount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bookmarksForCourse',
            field=models.ManyToManyField(related_name='bookmarksForCourse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='likesForArticle',
            field=models.ManyToManyField(related_name='likesForArticle', to=settings.AUTH_USER_MODEL),
        ),
    ]
