# Generated by Django 5.0.6 on 2024-06-19 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_image'),
        ('user', '0003_alter_reaction_reaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
        migrations.AddField(
            model_name='article',
            name='reactions',
            field=models.ManyToManyField(blank=True, default=[], related_name='articleReactions', to='user.reaction'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='commentLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
