# Generated by Django 4.1.4 on 2023-01-19 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='commentsCount',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lessonsCount',
        ),
        migrations.RemoveField(
            model_name='course',
            name='themesCount',
        ),
        migrations.RemoveField(
            model_name='course',
            name='viewCount',
        ),
    ]
