# Generated by Django 4.1.4 on 2023-01-26 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_coursereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereview',
            name='stars',
        ),
        migrations.AddField(
            model_name='coursereview',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
