# Generated by Django 4.1.4 on 2023-01-31 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_coursereview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomment',
            name='commentType',
            field=models.CharField(choices=[('review', 'review'), ('comment', 'comment')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='courseTask',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='course.coursetask'),
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='coursecomment',
            name='message',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.DeleteModel(
            name='CourseReview',
        ),
    ]
