# Generated by Django 4.1.7 on 2023-04-16 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, default=None, upload_to='profiles')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=168)),
                ('instagram', models.CharField(blank=True, max_length=1000)),
                ('facebook', models.CharField(blank=True, max_length=1000)),
                ('number', models.CharField(blank=True, max_length=12)),
                ('twitter', models.CharField(blank=True, max_length=1000)),
                ('github', models.CharField(blank=True, max_length=1000)),
                ('telegram', models.CharField(blank=True, max_length=1000)),
                ('website', models.URLField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
