# Generated by Django 4.1.4 on 2023-01-15 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('twitter', models.CharField(blank=True, max_length=1000)),
                ('github', models.CharField(blank=True, max_length=1000)),
                ('telegram', models.CharField(blank=True, max_length=1000)),
                ('website', models.URLField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bookmarkArticle', models.ManyToManyField(blank=True, default='', related_name='likeBookmark', to='course.course')),
                ('bookmarkCourses', models.ManyToManyField(blank=True, default='', related_name='bookmarkCourses', to='course.course')),
                ('courses', models.ManyToManyField(to='course.course')),
                ('likeArticle', models.ManyToManyField(blank=True, default='', related_name='likeArticle', to='course.course')),
                ('likeCourses', models.ManyToManyField(blank=True, default='', related_name='likeCourses', to='course.course')),
                ('tasks', models.ManyToManyField(to='course.coursetask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
