# Generated by Django 4.1.4 on 2023-01-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(blank=True, to='course.course'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='course.coursetask'),
        ),
    ]
