# Generated by Django 4.1.4 on 2023-01-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_description_course_about_and_more'),
        ('base', '0002_profile_cources_profile_tasks_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cources',
        ),
        migrations.AddField(
            model_name='profile',
            name='bookmarkArticle',
            field=models.ManyToManyField(blank=True, default='', related_name='likeBookmark', to='course.course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bookmarkCourses',
            field=models.ManyToManyField(blank=True, default='', related_name='bookmarkCourses', to='course.course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(to='course.course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='likeArticle',
            field=models.ManyToManyField(blank=True, default='', related_name='likeArticle', to='course.course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='likeCourses',
            field=models.ManyToManyField(blank=True, default='', related_name='likeCourses', to='course.course'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tasks',
            field=models.ManyToManyField(to='course.coursetask'),
        ),
    ]
