# Generated by Django 4.2.5 on 2023-10-03 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, default=None, upload_to='profiles')),
                ('backImage', models.ImageField(blank=True, default=None, upload_to='back_images')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=168)),
                ('Twitter', models.CharField(blank=True, max_length=1000)),
                ('GitHub', models.CharField(blank=True, max_length=1000)),
                ('GitLub', models.CharField(blank=True, max_length=1000)),
                ('Linkedin', models.CharField(blank=True, max_length=1000)),
                ('Telegram', models.CharField(blank=True, max_length=1000)),
                ('website', models.URLField(blank=True)),
                ('skills', models.CharField(blank=True, choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JavaScript', 'JavaScript'), ('TypeScript', 'TypeScript'), ('NodeJS', 'NodeJS'), ('Express', 'Express'), ('Next', 'Next'), ('Nust', 'Nust'), ('React', 'React'), ('Angular', 'Angular'), ('Vue', 'Vue'), ('GIT', 'GIT'), ('Python', 'Python'), ('Ruby', 'Ruby'), ('Django', 'Django'), ('Flask', 'Flask'), ('FastAPI', 'FastAPI'), ('Java', 'Java'), ('Spring', 'Spring'), ('Docker', 'Docker'), ('React Native', 'React Native'), ('Swift', 'Swift'), ('Kotlin', 'Kotlin'), ('PHP', 'PHP'), ('Laravel', 'Laravel'), ('C', 'C'), ('C++', 'C++'), ('C#', 'C#'), ('Blender', 'Blender'), ('Unity', 'Unity'), ('Unity', 'Unity'), ('Unreal Engine', 'Unreal Engine'), ('Maya', 'Maya'), ('Cinema 4D', 'Cinema 4D'), ('3D Modeling', '3D Modeling'), ('Blockchain Technology', 'Blockchain Technology'), ('Smart Contracts', 'Smart Contracts'), ('Solidity', 'Solidity'), ('Ethereum', 'Ethereum'), ('Hyperledger', 'Hyperledger'), ('Bitcoin', 'Bitcoin'), ('Cryptocurrency', 'Cryptocurrency'), ('Decentralized Applications (DApps)', 'Decentralized Applications (DApps)'), ('Graphic Design', 'Graphic Design'), ('UI/UX Design', 'UI/UX Design'), ('Adobe Photoshop', 'Adobe Photoshop'), ('Adobe Illustrator', 'Adobe Illustrator'), ('Sketch', 'Sketch'), ('Figma', 'Figma'), ('Prototyping', 'Prototyping'), ('Responsive Design', 'Responsive Design'), ('Typography', 'Typography'), ('Cybersecurity', 'Cybersecurity'), ('Ethical Hacking', 'Ethical Hacking'), ('Network Security', 'Network Security'), ('Vulnerability Assessment', 'Vulnerability Assessment'), ('Penetration Testing', 'Penetration Testing'), ('Security Auditing', 'Security Auditing'), ('Incident Response', 'Incident Response'), ('Security Tools (e.g., Nmap, Wireshark)', 'Security Tools (e.g., Nmap, Wireshark)'), ('Continuous Integration (CI)', 'Continuous Integration (CI)'), ('Continuous Deployment (CD)', 'Continuous Deployment (CD)'), ('Kubernetes', 'Kubernetes'), ('Infrastructure as Code (IaC)', 'Infrastructure as Code (IaC)'), ('Configuration Management', 'Configuration Management'), ('Monitoring and Logging', 'Monitoring and Logging')], max_length=1000)),
                ('interests', models.CharField(blank=True, choices=[('3d modeling', '3d modeling'), ('Communication', 'Communication'), ('Design', 'Design'), ('Education', 'Education'), ('Gaming', 'Gaming'), ('Lifehacks', 'Lifehacks'), ('Mobile', 'Mobile'), ('Productivity', 'Productivity'), ('Cybersecurity', 'Cybersecurity'), ('DevOps', 'DevOps'), ('Enterprise', 'Enterprise'), ('Health', 'Health'), ('Low/No Code', 'Low/No Code'), ('Music/Art', 'Music/Art'), ('Voice skills', 'Voice skills'), ('Blockchain', 'Blockchain'), ('E-commerce/Retail', 'E-commerce/Retail'), ('Fintech', 'Fintech'), ('Machine Learning/AI', 'Machine Learning/AI'), ('Robotic Process Automation', 'Robotic Process Automation'), ('Web', 'Web')], max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
