# Generated by Django 5.0.6 on 2024-05-21 21:44

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_interests_remove_profile_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('3d modeling', '3d modeling'), ('Communication', 'Communication'), ('Design', 'Design'), ('Education', 'Education'), ('Gaming', 'Gaming'), ('Lifehacks', 'Lifehacks'), ('Mobile', 'Mobile'), ('Productivity', 'Productivity'), ('Cybersecurity', 'Cybersecurity'), ('DevOps', 'DevOps'), ('Enterprise', 'Enterprise'), ('Health', 'Health'), ('Low/No Code', 'Low/No Code'), ('Music/Art', 'Music/Art'), ('Voice skills', 'Voice skills'), ('Blockchain', 'Blockchain'), ('E-commerce/Retail', 'E-commerce/Retail'), ('Fintech', 'Fintech'), ('Machine Learning/AI', 'Machine Learning/AI'), ('Robotic Process Automation', 'Robotic Process Automation'), ('Web', 'Web')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JavaScript', 'JavaScript'), ('TypeScript', 'TypeScript'), ('NodeJS', 'NodeJS'), ('Express', 'Express'), ('Next', 'Next'), ('Nust', 'Nust'), ('React', 'React'), ('Angular', 'Angular'), ('Vue', 'Vue'), ('GIT', 'GIT'), ('Python', 'Python'), ('Ruby', 'Ruby'), ('Django', 'Django'), ('Flask', 'Flask'), ('FastAPI', 'FastAPI'), ('Java', 'Java'), ('Spring', 'Spring'), ('Docker', 'Docker'), ('React Native', 'React Native'), ('Swift', 'Swift'), ('Kotlin', 'Kotlin'), ('PHP', 'PHP'), ('Laravel', 'Laravel'), ('C', 'C'), ('C++', 'C++'), ('C#', 'C#'), ('Blender', 'Blender'), ('Unity', 'Unity'), ('Unity', 'Unity'), ('Unreal Engine', 'Unreal Engine'), ('Maya', 'Maya'), ('Cinema 4D', 'Cinema 4D'), ('3D Modeling', '3D Modeling'), ('Blockchain Technology', 'Blockchain Technology'), ('Smart Contracts', 'Smart Contracts'), ('Solidity', 'Solidity'), ('Ethereum', 'Ethereum'), ('Hyperledger', 'Hyperledger'), ('Bitcoin', 'Bitcoin'), ('Cryptocurrency', 'Cryptocurrency'), ('Decentralized Applications (DApps)', 'Decentralized Applications (DApps)'), ('UI/UX Design', 'UI/UX Design'), ('Adobe Photoshop', 'Adobe Photoshop'), ('Adobe Illustrator', 'Adobe Illustrator'), ('Sketch', 'Sketch'), ('Figma', 'Figma'), ('Prototyping', 'Prototyping'), ('Responsive Design', 'Responsive Design'), ('Typography', 'Typography'), ('Cybersecurity', 'Cybersecurity'), ('Ethical Hacking', 'Ethical Hacking'), ('Network Security', 'Network Security'), ('Vulnerability Assessment', 'Vulnerability Assessment'), ('Penetration Testing', 'Penetration Testing'), ('Security Auditing', 'Security Auditing'), ('Incident Response', 'Incident Response'), ('Security Tools (e.g., Nmap, Wireshark)', 'Security Tools (e.g., Nmap, Wireshark)'), ('Continuous Integration (CI)', 'Continuous Integration (CI)'), ('Continuous Deployment (CD)', 'Continuous Deployment (CD)'), ('Kubernetes', 'Kubernetes'), ('Infrastructure as Code (IaC)', 'Infrastructure as Code (IaC)'), ('Configuration Management', 'Configuration Management'), ('Monitoring and Logging', 'Monitoring and Logging')], max_length=100, null=True),
        ),
    ]
