# Generated by Django 5.0.6 on 2024-05-21 22:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profile_interests_remove_profile_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500),
        ),
    ]
